CREATE TABLE Todos(
    todoId INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR NOT NULL,
    isComplete BIT DEFAULT 0,
    dueBy DATETIME NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);